#!/bin/sh

if [ "$1" = menu ]; then
	boot-menu-add-entry "$0" "kernel & rootfs on SD card"
	exit
fi

bootargs-ip
bootargs-display

global.bootm.image=/boot/linuximage
global.bootm.oftree=/boot/oftree
global.linux.bootargs.dyn.root="root=/dev/mmcblk0p2 rootfstype=ext3 rootwait rw"
