#!/bin/sh

if [ "$1" = menu ]; then
	boot-menu-add-entry "$0" "nand (UBI)"
	exit
fi

bootargs-ip
bootargs-display

global.bootm.image="/dev/nand0.kernel.bb"
global.bootm.oftree="/dev/nand0.oftree.bb"
global.linux.bootargs.dyn.root="root=ubi0:root ubi.mtd=root rootfstype=ubifs rw consoleblank=0"
