COMPATIBLE_MACHINE  = "^("
COMPATIBLE_MACHINE .= "k3"
COMPATIBLE_MACHINE .= "|phyboard-segin-imx6ul-6"
COMPATIBLE_MACHINE .= "|phyboard-segin-imx6ul-8"
COMPATIBLE_MACHINE .= "|mx8m-generic-bsp"
COMPATIBLE_MACHINE .= "|mx91-generic-bsp"
COMPATIBLE_MACHINE .= "|mx93-generic-bsp"
COMPATIBLE_MACHINE .= ")$"
