#!/bin/sh

. /env/expansions/imx6qdl-mira-peb-eval-01
#. /env/expansions/imx6qdl-phytec-lcd-018-peb-av-02
#. /env/expansions/imx6qdl-mira-enable-lvds
#. /env/expansions/imx6qdl-phytec-peb-wlbt-01

#Enable VM-010-BW-LVDS
of_camera_selection -a 0x48 -p 0 -b phyCAM-S+ VM-010-BW
