#!/bin/sh

#. /env/expansions/imx6qdl-phytec-lcd

# imx6qdl-phytec-lcd: 7" display
#of_display_timings -S /soc/aips-bus@02000000/ldb@020e0008/lvds-channel@0/display-timings/ETM0700G0DH6

# imx6qdl-phytec-lcd: 5.7" display
#of_display_timings -S /soc/aips-bus@02000000/ldb@020e0008/lvds-channel@0/display-timings/ETMV570G2DHU

# imx6qdl-phytec-lcd: 4.3" display
#of_display_timings -S /soc/aips-bus@02000000/ldb@020e0008/lvds-channel@0/display-timings/ETM0430G0DH6

# imx6qdl-phytec-lcd: 3.5" display
#of_display_timings -S /soc/aips-bus@02000000/ldb@020e0008/lvds-channel@0/display-timings/ETM0350G0DH6


#Enable VM-010-BW-LVDS
#of_camera_selection -a 0x48 -p 0 -b phyCAM-S+ VM-010-BW

#of_camera_selection -a 0x48 -p 1 -b phyCAM-S+ VM-010-BW
