#@TYPE: Machine
#@NAME: am62pxx-phyflex-libra-rdk-1-k3r5
#@DESCRIPTION: PHYTEC AM62Px phyFLEX Libra FPSC, 2GB RAM, HS-FS (R5F)
#@ARTICLENUMBERS: PD-05033-ALPHA.A0, PFL-G-06.A0

require conf/machine/include/phyk3r5.inc

MACHINEOVERRIDES =. "k3r5-am62pxx:phyflex-fpsc-g:phyflex-libra-rdk:am62px-phyflex-libra-rdk:"

SPL_BINARY = "tiboot3-am62px-hs-fs-phyflex-fpsc-g.bin"

UBOOT_MACHINE = ""
UBOOT_CONFIG = "sd"
UBOOT_CONFIG[sd] = "am62px_phyflex_fpsc_g_r5_defconfig,sdcard"
