#@TYPE: Machine
#@NAME: am62pxx-phyflex-libra-rdk-1
#@DESCRIPTION: PHYTEC AM62Px phyFLEX Libra FPSC, 2GB RAM, HS-FS
#@ARTICLENUMBERS: PD-05033-ALPHA.A0, PFL-G-06.A0

require conf/machine/include/phyam62pxx.inc

MACHINEOVERRIDES =. ":phyflex-fpsc-g:phyflex-libra-rdk:am62px-phyflex-libra-rdk:"

MACHINE_FEATURES += "can emmc gpu wifi bluetooth"

KERNEL_DEVICETREE = " \
    ti/k3-am62p5-phyflex-libra-rdk.dtb \
    ${KERNEL_OVERLAYS} \
"

UBOOT_MACHINE = "am62px_phyflex_fpsc_g_a53_defconfig"
