#@TYPE: Machine
#@NAME: phyboard-izar-am68x-3
#@DESCRIPTION: PHYTEC phyBOARD-Izar AM68x, 4-8 GB RAM, HS-FS
#@ARTICLENUMBERS: PCM-074-6T0834F2I.A1, PCM-074-6T0630B2I.A0

require conf/machine/include/phyam68x.inc

MACHINEOVERRIDES =. "phyboard-izar:"
MACHINE_FEATURES += "camera can emmc pci tpm2 gpu"

UBOOT_MACHINE = "phycore_am68x_a72_defconfig"

BBMULTICONFIG = "k3r5"
