#!/bin/sh

# change network settings in /env/network/eth0
# change mtd partition settings and automountpoints in /env/init/*

# set to false if you do not want to have colors
global.allow_color=false

# user (used for network filenames)
# global.user=none

# timeout in seconds before the default boot entry is started
global.autoboot_timeout=3

# list of boot entries. These are executed in order until one
# succeeds. An entry can be:
# - a filename in /env/boot/
# - a full path to a directory. All files in this directory are
#   treated as boot files and executed in alphabetical order
if [ $bootsource = mmc ]; then
	global.boot.default="sd-ext3 nand spi net"
elif [ $bootsource = nand ]; then
	global.boot.default="nand spi sd-ext3 net"
elif [ $bootsource = spi ]; then
	global.boot.default="spi nand sd-ext3 net"
elif [ $bootsource = net ]; then
	global.boot.default="net nand spi sd-ext3"
fi

global.linux.bootargs.base="consoleblank=0"
