#!/bin/sh

if [ -n "$nv.boot.default" ]; then
	exit
fi

if [ $bootsource = mmc -a $bootsource_instance = 1 ]; then
	global.boot.default="emmc mmc net"
elif [ $bootsource = mmc -a $bootsource_instance = 0 ]; then
	global.boot.default="mmc emmc net"
elif [ $bootsource = net ]; then
	global.boot.default="net emmc mmc"
fi
